# Generated by Django 5.1.6 on 2025-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0007_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True, verbose_name='First_name'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, default='User', max_length=50, null=True, verbose_name='Last_name'),
        ),
    ]
